
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kasantshnz
 */
public class Solicitud extends javax.swing.JFrame {

    public String contra;
    public String contra2;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Solicitud.class.getName());
    

        
    public Solicitud() {
        initComponents();
    contra = JOptionPane.showInputDialog("Ingrese su contraseña: ");
    contra2 = JOptionPane.showInputDialog("Ingrese su nombre: ");
    if  (contra.equals("123")){
      
        }else{
        JOptionPane.showMessageDialog(null, "La contraseña es incorrecta");
        System.exit(0);
     
    }
    this.setTitle("Calculadora");
    this.setLocationRelativeTo(null);
    jLabel2.setText("Bienvenido al sistema usuario "+ contra2 );
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calculadora de Descuentos");

        jLabel2.setText("jLabel2");

        jButton1.setText("Efectuar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel3.setText("Ingrese su nombre");

        jLabel4.setText("Total");

        jLabel5.setText("Tipo de cliente");

        jButton3.setText("Salida");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(jTextField3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double total, estudiante, docente, invitado,total2;
       String nombre = jTextField1.getText();
       total = Double.parseDouble(jTextField2.getText());
       String Cliente = jTextField3.getText();
       
       if (Cliente.equals("estudiante")){
           estudiante = total * 0.1;
           total2 = total-estudiante;
           String respuesta;
           respuesta = String.valueOf(total2);
           JOptionPane.showMessageDialog(null, "Cliente: "+nombre+" Tipo: "+ Cliente +
                   " Total: "+ total+ " Se aplica descuento de: "+ estudiante + " Total a Pagar: " + total2);
           
       
       }else if (Cliente.equals("docente")){
           docente = total * 0.2;
           total2 = total-docente;
           String respuesta;
           respuesta = String.valueOf(total2);
           JOptionPane.showMessageDialog(null, "Cliente: "+nombre+" Tipo: "+ Cliente +
                   " Total: "+ total+ " Se aplica descuento de: "+ docente + " Total a Pagar: " + total2);
           
       
       }else if (Cliente.equals("invitado")){
           invitado = total * 0;
           total2 = total-invitado;
           String respuesta;
           respuesta = String.valueOf(total2);
           JOptionPane.showMessageDialog(null, "Cliente: "+nombre+" Tipo: "+ Cliente +
                   " Total: "+ total+ " Se aplica descuento de: "+ invitado + " Total a Pagar: " + total2);
       }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jTextField1.setText(" ");
        jTextField2.setText(" ");
            jTextField3.setText(" ");
            double total, estudiante, docente, invitado,total2;
       String nombre = jTextField1.getText();
       total = Double.parseDouble(jTextField2.getText());
       String Cliente = jTextField3.getText();
       
       if (Cliente.equals("estudiante")){
           estudiante = total * 0.1;
           total2 = total-estudiante;
           String respuesta;
           respuesta = String.valueOf(total2);
           JOptionPane.showMessageDialog(null, "Cliente: "+nombre+" Tipo: "+ Cliente +
                   " Total: "+ total+ " Se aplica descuento de: "+ estudiante + " Total a Pagar: " + total2);
           
       
       }else if (Cliente.equals("docente")){
           docente = total * 0.2;
           total2 = total-docente;
           String respuesta;
           respuesta = String.valueOf(total2);
           JOptionPane.showMessageDialog(null, "Cliente: "+nombre+" Tipo: "+ Cliente +
                   " Total: "+ total+ " Se aplica descuento de: "+ docente + " Total a Pagar: " + total2);
           
       
       }else if (Cliente.equals("invitado")){
           invitado = total * 0;
           total2 = total-invitado;
           String respuesta;
           respuesta = String.valueOf(total2);
           JOptionPane.showMessageDialog(null, "Cliente: "+nombre+" Tipo: "+ Cliente +
                   " Total: "+ total+ " Se aplica descuento de: "+ invitado + " Total a Pagar: " + total2);
       }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Solicitud().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
